# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 204cfbdbbe87e621d4db066b1386cc84f177cc5b8444b933626085f97d036c2c7c259441d21450dc324388624ac5be8fc691540355e3283dabf3fe51f3cbc8cf

test:
  secret_key_base: aa07b81f4a866131107a3da5257d602cb33f494492b5a7740878c1857a3a94e130710e8f4314920cc74a6497023b8fe07764fa0f190d6468ea4c89a6a04aa73f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
